aws_region            = "ap-southeast-1"
vpc_name              = "eks-vpc"
vpc_cidr              = "10.0.0.0/16"
azs                   = ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
private_subnets       = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
public_subnets        = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
cluster_name          = "cluster"
cluster_version       = "1.32"
instance_types        = ["m6g.large"]
ami_type              = "AL2023_ARM_64_STANDARD"
min_size              = 3
max_size              = 5
desired_size          = 3
node_group_label      = "image-api-node-group"
efs_name              = "eks-efs"
vpc_cidr_block        = ["10.0.0.0/16"]
environment           = "dev"
domain_name           = "example.com"
waf_name              = "image-api-waf"
prometheus_chart_name = "kube-prometheus-stack"
monitoring_namespace  = "monitoring"
rate_limit            = 10000
